
package visao;

import utils.GerenciadorJanelas;

public class TelaPrincipal extends javax.swing.JFrame {
    GerenciadorJanelas gerenciador; // Gerenciador das Janelas Internas

    // Construtor
    public TelaPrincipal() {
        initComponents();
        this.gerenciador = new GerenciadorJanelas(jDesktopPane);
    }

    // Métodos
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        btnPessoal = new javax.swing.JButton();
        btnAgendamento = new javax.swing.JButton();
        btnProfissional = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblPessoal = new javax.swing.JLabel();
        lblProfissional = new javax.swing.JLabel();
        lblAgendamentos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmNovo = new javax.swing.JMenu();
        jmiNovoFamiliar = new javax.swing.JMenuItem();
        jmiNovoProfissional = new javax.swing.JMenuItem();
        jmiNovoAtendimento = new javax.swing.JMenuItem();
        jmiNovoEmergencia = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenu();
        jmiEditarPessoal = new javax.swing.JMenuItem();
        jmiEditarProfissional = new javax.swing.JMenuItem();
        jmiEditarAtendimento = new javax.swing.JMenuItem();
        jmiEditarResultados = new javax.swing.JMenuItem();
        jmView = new javax.swing.JMenu();
        jmiViewPessoal = new javax.swing.JMenuItem();
        jmiViewProfissional = new javax.swing.JMenuItem();
        jmiViewAtendimento = new javax.swing.JMenuItem();
        jmiViewResultados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISCOIMP - Sistema de Controle de Informações Médicas Pessoal");
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        jDesktopPane.setPreferredSize(new java.awt.Dimension(400, 265));

        btnPessoal.setText("Suas Informações");

        btnAgendamento.setText("Agendamentos");

        btnProfissional.setText("Profissionais");

        btnResultados.setText("Resultados");

        lblTitle.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        lblTitle.setText("SISCOIMP");

        lblPessoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pessoal_64px.png"))); // NOI18N

        lblProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profissional_64px.png"))); // NOI18N

        lblAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agenda_64px.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Resultado_64px.png"))); // NOI18N

        jDesktopPane.setLayer(btnPessoal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btnAgendamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btnProfissional, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btnResultados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblPessoal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblProfissional, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblAgendamentos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPessoal)
                                .addComponent(lblProfissional)
                                .addComponent(lblAgendamentos, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnProfissional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTitle))
                .addGap(174, 174, 174))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPessoal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProfissional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgendamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jmNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Novo_32px.png"))); // NOI18N
        jmNovo.setMnemonic('N');
        jmNovo.setText("Novo");

        jmiNovoFamiliar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiNovoFamiliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Familiar_24px.png"))); // NOI18N
        jmiNovoFamiliar.setText("Familiar");
        jmiNovoFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovoFamiliarActionPerformed(evt);
            }
        });
        jmNovo.add(jmiNovoFamiliar);

        jmiNovoProfissional.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiNovoProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profissional_24px.png"))); // NOI18N
        jmiNovoProfissional.setText("Profissional");
        jmiNovoProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovoProfissionalActionPerformed(evt);
            }
        });
        jmNovo.add(jmiNovoProfissional);

        jmiNovoAtendimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiNovoAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendimento_24px.png"))); // NOI18N
        jmiNovoAtendimento.setText("Consulta/Exames");
        jmiNovoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovoAtendimentoActionPerformed(evt);
            }
        });
        jmNovo.add(jmiNovoAtendimento);

        jmiNovoEmergencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiNovoEmergencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Emergencia_24px.png"))); // NOI18N
        jmiNovoEmergencia.setText("Informações de Emergência");
        jmiNovoEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovoEmergenciaActionPerformed(evt);
            }
        });
        jmNovo.add(jmiNovoEmergencia);

        jMenuBar1.add(jmNovo);

        jmEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.png"))); // NOI18N
        jmEditar.setMnemonic('E');
        jmEditar.setText("Editar");

        jmiEditarPessoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pessoal_24px.png"))); // NOI18N
        jmiEditarPessoal.setText("Informações Pessoais");
        jmEditar.add(jmiEditarPessoal);

        jmiEditarProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profissional_24px.png"))); // NOI18N
        jmiEditarProfissional.setText("Profissional");
        jmEditar.add(jmiEditarProfissional);

        jmiEditarAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agenda_24px.png"))); // NOI18N
        jmiEditarAtendimento.setText("Agendamentos");
        jmEditar.add(jmiEditarAtendimento);

        jmiEditarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Resultado_24px.png"))); // NOI18N
        jmiEditarResultados.setText("Resultados");
        jmEditar.add(jmiEditarResultados);

        jMenuBar1.add(jmEditar);

        jmView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/View_32px.png"))); // NOI18N
        jmView.setMnemonic('V');
        jmView.setText("Visualizar");

        jmiViewPessoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pessoal_24px.png"))); // NOI18N
        jmiViewPessoal.setText("Seus Dados");
        jmView.add(jmiViewPessoal);

        jmiViewProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profissional_24px.png"))); // NOI18N
        jmiViewProfissional.setText("Médicos/Terapeutas");
        jmView.add(jmiViewProfissional);

        jmiViewAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agenda_24px.png"))); // NOI18N
        jmiViewAtendimento.setText("Agendamentos");
        jmView.add(jmiViewAtendimento);

        jmiViewResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Resultado_24px.png"))); // NOI18N
        jmiViewResultados.setText("Resultados");
        jmView.add(jmiViewResultados);

        jMenuBar1.add(jmView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNovoFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovoFamiliarActionPerformed
        gerenciador.abrirJanela(NovoFamiliar.getInstance());
    }//GEN-LAST:event_jmiNovoFamiliarActionPerformed

    private void jmiNovoProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovoProfissionalActionPerformed
        gerenciador.abrirJanela(NovoProfissional.getInstance());
    }//GEN-LAST:event_jmiNovoProfissionalActionPerformed

    private void jmiNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovoAtendimentoActionPerformed
        gerenciador.abrirJanela(NovoAtendimento.getInstance());
    }//GEN-LAST:event_jmiNovoAtendimentoActionPerformed

    private void jmiNovoEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovoEmergenciaActionPerformed
        gerenciador.abrirJanela(NovoEmergencia.getInstance());
    }//GEN-LAST:event_jmiNovoEmergenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JButton btnPessoal;
    private javax.swing.JButton btnProfissional;
    private javax.swing.JButton btnResultados;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmEditar;
    private javax.swing.JMenu jmNovo;
    private javax.swing.JMenu jmView;
    private javax.swing.JMenuItem jmiEditarAtendimento;
    private javax.swing.JMenuItem jmiEditarPessoal;
    private javax.swing.JMenuItem jmiEditarProfissional;
    private javax.swing.JMenuItem jmiEditarResultados;
    private javax.swing.JMenuItem jmiNovoAtendimento;
    private javax.swing.JMenuItem jmiNovoEmergencia;
    private javax.swing.JMenuItem jmiNovoFamiliar;
    private javax.swing.JMenuItem jmiNovoProfissional;
    private javax.swing.JMenuItem jmiViewAtendimento;
    private javax.swing.JMenuItem jmiViewPessoal;
    private javax.swing.JMenuItem jmiViewProfissional;
    private javax.swing.JMenuItem jmiViewResultados;
    private javax.swing.JLabel lblAgendamentos;
    private javax.swing.JLabel lblPessoal;
    private javax.swing.JLabel lblProfissional;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
